/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 better-noAni-posi-draco.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/better-noAni-posi-draco.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StarSparrow_Wing002.geometry} material={materials.StarSparrow_Material} position={[-1.769, 0.183, 1.262]} rotation={[0, 0, 1.336]} scale={0.794} />
    </group>
  )
}

useGLTF.preload('/better-noAni-posi-draco.glb')
